import './globals.css'

export const metadata = {
  title: 'Nextjd App Router',
  description: 'Generated by NextJs',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <header>
          <p>This is header</p>
        </header>
        {children}
        <footer>
          <p>This is footer</p>
        </footer>
      </body>

    </html>
  )
}
