import './globals.css'

export const metadata = {
  title: 'Nextjs App Router',
  description: 'Generated by NextJs',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen text-4xl ">
          {children}
        </div>
      </body>
    </html>
  )
}
