import React from 'react';
import Sidebar from '../components/shared/Sidebar';

export const metadata = {
    title: 'Nextjs Dashboard',
    description: 'Generated by NextJs',
}

const DashboardLayout = ({ children }) => {
    return (
        <div className='flex'>
            <Sidebar />
            <div className='w-full'>
                {children}
            </div>
        </div>
    );
};

export default DashboardLayout;